name: CI Keycloak plugins
on: [workflow_dispatch]

env:
  REGISTRY_SERVER: rg.fr-par.scw.cloud/senior-gold-docker-registry

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY_SERVER }}/senior-gold-keycloak-plugins
          tags: |
            type=semver,enable=true,pattern={{version}},value=1.0.0
          flavor: |
            latest=false
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          context: "{{defaultContext}}:."
          tags: ${{ steps.metadata.outputs.tags }}
